### ISSUE TITLE
Photographer may pay MomentPlus Dues from ShakeItPhoto

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/mp-shake-it-photo#16]
ShakeItPhoto Plus would start with zero additional features, and be purely a call-to-action for continued maintenance and development on ShakeItPhoto.

```features/sustainable-maintenance.feature
Feature: Maintenance Dues
  In order to know that ShakeIt Photo will play nicely on modern iOS devices in a timely manner
  I want to fund the continued development of MomentPark apps

  Scenario: Prompting to pay Dues
    Given I am not paying any Moment Park Dues
    And I have not been prompted to pay dues in the last 30 days
    And I installed the app 60 days or more ago
    When I launch the app 
    Then I am prompted to pay Moment Park Dues

  Scenario: Annual Dues - Maintainer
    Given I am not paying any Moment Park Dues
    When I pay my Annual Maintainer Dues
    Then I am no longer prompted to pay any other Dues
    And I can tell I have upgraded to Maintainer 
  
  Scenario: Annual Dues - Enhancer
    Given I am not paying any Moment Park Dues
    When I pay my Annual Enhancer Dues
    Then I am no longer prompted to pay any other Dues
    And I can tell I have upgraded to Ehancer 

  Scenario: Monthly Dues - Enhancer
    Given I am not paying any Moment Park Dues
    When I pay my Monthly Enhancer Dues
    Then I am no longer prompted to pay any other Dues
    And I can tell I have upgraded to Ehancer 
```

## Potential Hooks:
- "We need your help keeping ShakeItPhoto alive."
- "Support Indie App Developers"
- "Fund and Influence ShakeItPhoto's Expedition"
- "Help Us Reach our Goal of ~$75,000/yr to pay a part-time Mobile App developer"

## How?

- [ ] Write copy for call-to-action - @zspencer
- [ ] Write copy for the announcement - @zspencer 
- [ ] Pick a price for the in-app purchase - @maximegalon5 
    - Enhance: $9.99/yr, $2/mo
    - Maintain: $4.99/yr
- [ ] Spike [an in-app purchase](https://developer.apple.com/in-app-purchase/) in Swift for [monthly and annual plus membership subscriptions](https://developer.apple.com/app-store/subscriptions/) - @theInternauts 

##  This Issue May Be Closed When
- [ ] We have released a TestFlight Build with Plus dues built into it
- [ ] We have copy written for the release announcement
