### ISSUE TITLE
Provide links to the Shake It Photo support channels,source code, and bug tracker within the app

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/mp-shake-it-photo#19]
## This issue may be closed when
- [ ] The "settings" page has a link to:
  - [ ] [The support inbox](http://www.momentpark.com/contact-us)
  - [ ] [The new issue page](https://github.com/zinc-collective/mp-shake-it-photo/issues/new)
  - [ ] [The project readme](https://github.com/zinc-collective/mp-shake-it-photo#readme)
- [ ] There is a build on TestFlight that indicates that this feature is available for testing
- [ ] The Changelog includes release notes for this feature. 

## Feature Definition
```features/improving-shake-it-photo.feature

In order for ShakeIt Photo to continue to delight me
I want affordances that allow me to exert influence upon its product trajectory

Scenario: Discovering Influence and Control Affordances
  Given I am on the ShakeItPhoto Options screen
  Then I can see a link to request help
  And I can see a link to report a bug
  And I can see a link to the project source code
```
