### ISSUE TITLE
Photographer may take photos with reduced compression artifacts

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/mp-shake-it-photo#29]
## TODO
- [ ] Reduce the JPEG Compression for everything
- [ ] Maybe? Expose configuration for setting the JPEG Compression
- [ ] Maybe? Take photos using the high resolution mode?
- [ ] Maybe? Expose configuration for taking photos in high resolution mode?

**Comment by zspencer** [comment]
Requested from a Sponsor!

> Would like less banding in skies
> Message: Since I subscribe to support you folks (for a tiny sum per month), I suppose that I'm entitled to share an opinion with you occasionally. First, thank you again for ShakeItPhoto. I continue to use it almost every day.
> 
> ShakeItPhoto does have a limitation for my purposes, which is that large areas of blue sky often end up with visible banding. I suppose that's a result of JPEG compression, a feature that I'm pretty sure that Polaroid cameras didn't have. I suppose that reducing the amount of JPEG compression might be a fairly straightforward change to make in the next version, which I hope there will be at some point.
> 
> Thanks!
>
> Regards,

https://groups.google.com/a/zinc.coop/d/msgid/momentpark/822332867.31379.1630379090060.JavaMail.root%40v6-aux-84985555cd-5jq4l
