### ISSUE TITLE
"Share" function may not work on modern iOS devices

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/mp-shake-it-photo#31]
This may be another permissions issue.

##  TODO
- [ ] For 3.4.0
  - [ ] Make sure our permissions are set up correctly
  - [ ] Attempt to update the "Share" Widget to [the latest Apple APIs](https://developer.apple.com/documentation/social#overview)?
- [ ] For 3.X - Eventually
  - [ ] Upgrade to the most up-to-date interface guidelines + sdk for sharing content out from an app

**Comment by zspencer** [comment]
> Subject: Share function
>
> Message: The share to Facebook function does not work

https://groups.google.com/a/zinc.coop/d/msgid/momentpark/1174960239.19745.1631263297151.JavaMail.root%40v6-aux-5786887fbf-8dq5b?utm_medium=email&utm_source=footer

**Comment by zspencer** [comment]
@theInternauts - I believe this was fixed as part of the 3.5.0 release? Is that correct?

I've replied to the client and closed the issue.

**Comment by zspencer** [comment]
User has reported that the Share functionality still does not work.
