### ISSUE TITLE
Release Shake It Photo 3.2.6

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/mp-shake-it-photo#6]
In order to have all the new goodies in ShakeItPhoto
As a fun-focused photographer
I would like a new release of ShakeIt Photo

## This Issue Can Be Closed When
- [ ] ~@zspencer - A Test Plan has been written and shared with the world~
- [ ] ~@theInternauts  - The Support email has been updated to 'momentpark@zinc.coop' for test-flight and in the app~
- [ ] ~@theInternauts  - The 3.2.6 release has been pushed to the ShakeItPhoto Test Flight!~
- [ ] ~@zspencer - The Zinc Community has been informed that we have a build ready for testing~
- [ ] ~@zspencer - The 3.2.6 release has been reviewed by the ShakeItPhoto Test Flight Team (We may need to create one.)~
- [x] @theInternauts - The 3.2.6 release has been submitted to Apple for final review
- [x] @theInternauts  - The 3.2.6 release has been approved by Apple
- [ ] @zspencer - The Subscribers to the Moment Park newsletter have been informed of the 3.2.6 release!
- [ ] @zspencer - This is the only issue in the [ShakeItPhoto 3.2.6 Milestone](https://github.com/zinc-collective/mp-shake-it-photo/milestone/1)

**Comment by theInternauts** [comment]
This milestone was has been eclipsed by the release of v3.3.0 that supports iOS 14.1+
